<#
.SYNOPSIS
    Configures IBKR Gateway for automatic paper trading login.

.DESCRIPTION
    Modifies jts.ini to enable auto-login with stored credentials.
    Credentials can be provided interactively or from secrets file.

.PARAMETER Username
    IBKR paper trading username.

.PARAMETER Password
    IBKR paper trading password.

.PARAMETER ApplyToInstallPath
    Also write jts.ini into the Gateway install folder (some versions read from there).

.EXAMPLE
    .\setup-ibkr-autologin.ps1
    .\setup-ibkr-autologin.ps1 -Username "myuser" -Password "mypass"
#>

[CmdletBinding()]
param(
    [string]$Username,
    [string]$Password,
    [string]$GatewayPath,
    [switch]$ApplyToInstallPath
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = (Get-Item $ScriptDir).Parent.Parent.FullName

# Source common functions
. (Join-Path $ScriptDir "utils\common.ps1")

Write-Host "`n=== IBKR Gateway Auto-Login Configuration ===" -ForegroundColor Cyan

# Load .env if exists (secrets + optional config path override)
$EnvFile = Join-Path $RepoRoot ".env"
Import-EnvFile -EnvFilePath $EnvFile

# Load config.json
$config = Import-GatewayConfig
$paperPort = [int](Get-GatewayConfigValue $config "paper_gateway_port" 4002)
$livePort = [int](Get-GatewayConfigValue $config "live_gateway_port" 4001)
$controlBaseDir = Get-GatewayConfigValue $config "control_dir" "C:\ProgramData\mm-ibkr-gateway"
$controlFile = Join-Path $controlBaseDir "control.json"
$tradingMode = "paper"
if (Test-Path $controlFile) {
    try {
        $controlState = Get-Content -Path $controlFile -Raw | ConvertFrom-Json
        if ($controlState.trading_mode) { $tradingMode = $controlState.trading_mode }
    } catch {
        $tradingMode = "paper"
    }
}

# Determine gateway path
if (-not $GatewayPath) {
    $GatewayPath = Get-GatewayConfigValue $config "ibkr_gateway_path" $null
}
if (-not $GatewayPath) {
    $GatewayPath = $env:IBKR_GATEWAY_PATH
}
if (-not $GatewayPath) {
    # Try to find it
    $possiblePaths = @(
        "$env:USERPROFILE\Jts\ibgateway",
        "C:\Jts\ibgateway",
        "${env:ProgramFiles}\Jts\ibgateway",
        "${env:ProgramFiles(x86)}\Jts\ibgateway"
    )
    foreach ($path in $possiblePaths) {
        $versions = Get-ChildItem $path -Directory -ErrorAction SilentlyContinue | Sort-Object Name -Descending
        if ($versions) {
            $GatewayPath = $versions[0].FullName
            break
        }
    }
}

if (-not $GatewayPath -or -not (Test-Path $GatewayPath)) {
    Write-Host "ERROR: IBKR Gateway path not found." -ForegroundColor Red
    Write-Host "Please specify path with -GatewayPath or set ibkr_gateway_path in config.json" -ForegroundColor Red
    exit 1
}

Write-Host "Gateway path: $GatewayPath" -ForegroundColor Gray

# Find or create jts.ini location
# IBKR Gateway typically stores config in user's Jts folder
$JtsConfigDir = "$env:USERPROFILE\Jts"
$JtsIniPath = Join-Path $JtsConfigDir "jts.ini"

if (-not (Test-Path $JtsConfigDir)) {
    New-Item -ItemType Directory -Path $JtsConfigDir -Force | Out-Null
    Write-Host "Created Jts config directory: $JtsConfigDir"
}

# Load credentials from secrets file if not provided
if (-not $Username -or -not $Password) {
    $credFile = Join-Path $RepoRoot "secrets\ibkr_credentials.json"
    if (Test-Path $credFile) {
        $creds = Get-Content $credFile | ConvertFrom-Json
        if (-not $Username) { $Username = $creds.username }
        if (-not $Password) { $Password = $creds.password }
        Write-Host "Loaded credentials from secrets file" -ForegroundColor Gray
    }
}

# Prompt if still missing
if (-not $Username) {
    $Username = Read-Host "IBKR Paper Username"
}
if (-not $Password) {
    $securePassword = Read-Host "IBKR Paper Password" -AsSecureString
    $Password = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($securePassword)
    )
}

if (-not $Username -or -not $Password) {
    Write-Host "ERROR: Username and password are required." -ForegroundColor Red
    exit 1
}

# Create jts.ini content for paper trading auto-login
# Note: IBKR Gateway uses specific settings for auto-login
$gatewayPort = if ($tradingMode -eq "live") { $livePort } else { $paperPort }
$jtsContent = @"
[IBGateway]
# Auto-login configuration for paper trading
# Generated by mm-ibkr-gateway setup on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

# Connection mode: paper (1) or live (0)
tradingMode=1

# Auto-login settings
s3store=true
ApiOnly=true
useRemoteSettings=false
StoreSettingsOnServer=false

# Paper account credentials
PaperLogin=$Username
PaperPassword=$Password

# General settings
WriteDebug=false
UseSSL=true
AcceptIncomingConnectionAction=accept
AcceptNonBrokerageAccountWarning=true
ExistingSessionDetectedAction=primary
TrustedIPs=127.0.0.1

# API settings
LocalServerPort=$gatewayPort
ActiveLocale=en
UseGUITrust=false

[Logon]
# Use paper trading login
usePaperTrading=1
useRemoteSettings=false
Displayed=1
displayedpw=1
s3store=true
Locale=en
TradingMode=p

[Communication]
# Allow API connections
AllowInternalAPI=true
AllowLocalConnections=true

# Trusted API IPs (localhost for this deployment)
TrustedIPs=127.0.0.1
"@

# Backup existing jts.ini if present
if (Test-Path $JtsIniPath) {
    $backupPath = "$JtsIniPath.backup.$(Get-Date -Format 'yyyyMMdd_HHmmss')"
    Copy-Item $JtsIniPath $backupPath
    Write-Host "Backed up existing jts.ini to: $backupPath" -ForegroundColor Gray
}

# Write jts.ini
Set-Content -Path $JtsIniPath -Value $jtsContent -Encoding UTF8
Write-Host "Created jts.ini at: $JtsIniPath" -ForegroundColor Green

# Optionally also write to the Gateway install directory (some versions read from there)
if ($ApplyToInstallPath) {
    $installIniPath = Join-Path $GatewayPath "jts.ini"
    if (Test-Path $installIniPath) {
        $backupInstall = "$installIniPath.backup.$(Get-Date -Format 'yyyyMMdd_HHmmss')"
        Copy-Item $installIniPath $backupInstall -ErrorAction SilentlyContinue
        Write-Host "Backed up install jts.ini to: $backupInstall" -ForegroundColor Gray
    }
    Set-Content -Path $installIniPath -Value $jtsContent -Encoding UTF8
    Write-Host "Applied jts.ini to install path: $installIniPath" -ForegroundColor Green
}

# Security warning
Write-Host "`n=== SECURITY WARNING ===" -ForegroundColor Yellow
Write-Host "IBKR Gateway credentials are stored in PLAINTEXT in jts.ini." -ForegroundColor Yellow
Write-Host "This is an IBKR Gateway limitation, not a flaw in this script." -ForegroundColor Yellow
Write-Host ""
Write-Host "Recommendations:" -ForegroundColor Cyan
Write-Host "  1. Use a dedicated paper trading account for this deployment"
Write-Host "  2. Enable Windows EFS encryption on $JtsConfigDir"
Write-Host "  3. Ensure laptop has full-disk encryption (BitLocker)"
Write-Host "  4. Never commit jts.ini to version control"
Write-Host ""

# Provide EFS encryption command
Write-Host "To encrypt with EFS (optional):" -ForegroundColor Gray
Write-Host "  cipher /e `"$JtsConfigDir`"" -ForegroundColor White
Write-Host ""

# ============================================================================
# IBAutomater Setup (Java agent for auto-login and UI automation)
# ============================================================================

Write-Host "`n=== Setting up IBAutomater ===" -ForegroundColor Cyan

$StateDir = "C:\ProgramData\mm-ibkr-gateway"
$JarSource = Join-Path $ScriptDir "ibautomater\IBAutomater.jar"
$JarTarget = Join-Path $StateDir "IBAutomater.jar"
$AgentConfigPath = Join-Path $StateDir "IBAutomater.json"

# Create state directory if needed
if (-not (Test-Path $StateDir)) {
    New-Item -ItemType Directory -Path $StateDir -Force | Out-Null
    Write-Host "Created state directory: $StateDir" -ForegroundColor Gray
}

# Copy IBAutomater.jar
if (-not (Test-Path $JarSource)) {
    Write-Host "WARNING: IBAutomater.jar not found at $JarSource" -ForegroundColor Yellow
    Write-Host "IBAutomater will be unavailable for auto-login" -ForegroundColor Yellow
    Write-Host "The gateway will prompt for manual login" -ForegroundColor Gray
} else {
    try {
        if ((Test-Path $JarTarget) -and (Get-Item $JarSource).Length -eq (Get-Item $JarTarget).Length) {
            Write-Host "IBAutomater.jar already in place, skipping copy" -ForegroundColor Gray
        } else {
            Copy-Item $JarSource $JarTarget -Force -ErrorAction Stop
            Write-Host "Copied IBAutomater.jar to: $JarTarget" -ForegroundColor Green
        }
    } catch {
        Write-Host "ERROR: Could not copy IBAutomater.jar: $_" -ForegroundColor Red
        exit 1
    }

    # Create IBAutomater config file
    $gatewayPort = if ($tradingMode -eq "live") { $livePort } else { $paperPort }
    
    $agentConfig = @(
        $Username
        $Password
        $tradingMode
        $gatewayPort
        "false"  # exportLogs
        "false"  # isRestart
    ) -join "`n"
    
    try {
        Set-Content -Path $AgentConfigPath -Value $agentConfig -Encoding UTF8 -ErrorAction Stop
        Write-Host "Created IBAutomater config: $AgentConfigPath" -ForegroundColor Green
    } catch {
        Write-Host "WARNING: Could not write IBAutomater config: $_" -ForegroundColor Yellow
    }

    # Update ibgateway.vmoptions to enable the Java agent
    $vmOptionsPath = Join-Path $GatewayPath "ibgateway.vmoptions"
    $javaAgentLine = "-javaagent:$JarTarget=$AgentConfigPath"
    
    try {
        if (Test-Path $vmOptionsPath) {
            $vmLines = @(Get-Content $vmOptionsPath)
            # Remove any existing IBAutomater entries
            $vmLines = $vmLines | Where-Object { $_ -notmatch "IBAutomater\.jar" }
            # Add new entry
            $vmLines += $javaAgentLine
            Set-Content -Path $vmOptionsPath -Value $vmLines -Encoding UTF8
            Write-Host "Updated ibgateway.vmoptions with javaagent: $vmOptionsPath" -ForegroundColor Green
        } else {
            Set-Content -Path $vmOptionsPath -Value @($javaAgentLine) -Encoding UTF8
            Write-Host "Created ibgateway.vmoptions with javaagent: $vmOptionsPath" -ForegroundColor Green
        }
    } catch {
        Write-Host "WARNING: Could not update ibgateway.vmoptions: $_" -ForegroundColor Yellow
        Write-Host "You may need to manually add: $javaAgentLine" -ForegroundColor Yellow
    }
}

Write-Host "`n=== Configuration Complete ===" -ForegroundColor Green
Write-Host ""
Write-Host "Summary:" -ForegroundColor Cyan
Write-Host "  jts.ini:              $JtsIniPath"
Write-Host "  IBAutomater JAR:      $JarTarget"
Write-Host "  IBAutomater Config:   $AgentConfigPath"
Write-Host "  VM Options:           $vmOptionsPath"
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Test IBKR Gateway manually: Start it and verify auto-login works"
Write-Host "  2. If login fails, check $AgentConfigPath and credentials"
Write-Host "  3. Run install-gateway-service.ps1 to configure the Windows service"
Write-Host ""
